### ISSUE TITLE
 python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by xiaotiancai899** [SteveImmanuel/SegGPT-FineTune#3]
When I run this command  
pip install -r requirements.txt
An issue occured.

 Running command git checkout -q f3a463104ad99e55b87422b5753ea34723ee272e
  Resolved https://github.com/facebookresearch/detectron2.git to commit f3a463104ad99e55b87422b5753ea34723ee272e
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-k4dxz5ey/detectron2_f3993bd7d20c4304b36cbe885fe2f2aa/setup.py", line 10, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

What can I do to fix it?

**Comment by SteveImmanuel** [comment]
It seems like `torch` package is not installed properly in your environment
