### ISSUE TITLE
OEM dataset

### ISSUE THREAD

**Issue by xiaotiancai899** [SteveImmanuel/SegGPT-FineTune#4]
Thanks for your good work! 
As you mentioned, you used the OEM dataset. Could you please put the dataset folder into the model folder so that make the whole project more complete?

**Comment by SteveImmanuel** [comment]
This repo I specifically develop to serve as general purpose template for fine-tuning so I am not going to commit to such project structure. However, you can easily override the dataloader to support your own custom dataset.
