### ISSUE TITLE
checkpoint file

### ISSUE THREAD

**Issue by xiaotiancai899** [SteveImmanuel/SegGPT-FineTune#5]
Would you please upload the tuning.pt file mentioned in the inference.py file? As a result, I can use the trained and tuned SegGPT model to predict other images. Thanks a lot!!

**Comment by SteveImmanuel** [comment]
Please refer to my other repo specifically for that purpose: https://github.com/SteveImmanuel/OEM-Few-Shot-Learnable-Prompt
You can find the checkpoint in the release
