### ISSUE TITLE
1

### ISSUE THREAD

**Issue by segnaro9** [SteveImmanuel/SegGPT-FineTune#9]

**Comment by SteveImmanuel** [comment]
Yes of course!

**Comment by segnaro9** [comment]
So do I need to make some additional adjustments with your code? thank you so much

**Comment by SteveImmanuel** [comment]
If your data follows this [format](https://github.com/SteveImmanuel/SegGPT-FineTune?tab=readme-ov-file#dataset), then you simply need to create the config file specific for your dataset (refer to `configs/base.json` as template). Otherwise, you need to implement the dataloader for your dataset.

**Comment by segnaro9** [comment]
Thank you very much for your reply, I will use the pascal voc dataset.
